create table public.fungi_regional_stats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fungi_id integer not null,
  region_code text not null,
  obs_count integer not null,
  constraint fungi_reagional_stats_pkey primary key (id),
  constraint unique_fungi_region_stat unique (fungi_id, region_code),
  constraint fungi_reagional_stats_fungi_id_fkey foreign KEY (fungi_id) references fungi (id) on delete CASCADE
) TABLESPACE pg_default;