name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Add 200.html fallback
        run: cp dist/index.html dist/200.html

      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 

# put SURGE_DOMAIN (without www or https) and SURGE_TOKEN in your repository secrets (Settings > Secrets and variables > Actions > New repository secret)